import Head from "next/head";
import Footer from "../components/Footer";
import Navigation from "../components/Navigation/Navigation";
import Search from "../components/search/Search";
import Slider from "../components/Slider/Slider";

export default function Home() {
  return (
    <div>
      <Head>
        <title>UpHire</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          data-n-head="ssr"
          data-hid="twitter:title"
          name="twitter:title"
          content="Upwork | The World’s Work Marketplace"
        />
        <meta
          data-n-head="ssr"
          data-hid="description"
          name="description"
          content="Upwork connects businesses with independent professionals and agencies around the globe. Where companies and freelancers work together in new ways that unlock their potential."
        />
        <meta
          data-n-head="ssr"
          data-hid="og:description"
          property="og:description"
          content="Upwork connects businesses with independent professionals and agencies around the globe. Where companies and freelancers work together in new ways that unlock their potential."
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navigation */}
      <Navigation />
      {/* Slider */}
      <Slider />
      {/* Main Content 1 */}

      {/* <Search /> */}
      {/* Main Content 2 */}

      {/* Main Content 3 */}

      {/* Footer */}
      <Footer />
    </div>
  );
}
